-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgS+KlWdcLyhs7H2Qq
zpByP6AFKTdsc/mDxtyP7BAZbmagCgYIKoZIzj0DAQehRANCAARPN5nYNI7zMQNH
hOmHUfFZTVWp7C2/cPLE1pxBEAHrrOGm11wKVkuis8Ps2tlKFVH+c7nDPfyJWPLj
oQeSjIIn
-----END PRIVATE KEY-----